# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cat_mult_fw_cpp <- function(allprobs, gamma, m, n, delta) {
    .Call('_vinkphd_cat_mult_fw_cpp', PACKAGE = 'vinkphd', allprobs, gamma, m, n, delta)
}

