#' Obtain hidden state sequence for each subject using the Viterbi
#' algorithm
#'
#' \code{vit_mHMM} obtains the most likely state sequence (for each subject)
#' from an object of class \code{mHMM} (generated by the function
#' \code{mHMM()}), using (an extended version of) the Viterbi algorithm. This is
#' also known as global decoding. Optionally, the state probabilities
#' themselves at each point in time can also be obtained.
#'
#' Note that local decoding is also possible, by inferring the most frequent
#' state at each point in time for each subject from the sampled state path at
#' each iteration of the MCMC algorithm. This information is contained in the
#' output object \code{return_path} of the function \code{mHMM()}.
#'
#' @param models An object of class \code{mHMM}, generated
#'   by the function \code{\link{mHMM}}.
#' @param s_data Data file.
#' @param burn_in The number of iterations to be discarded from the MCMC
#'   algorithm when inferring the transition probability matrix gamma and the
#'   emission distribution of (each of) the dependent variable(s) for each
#'   subject from \code{s_data}. If omitted, defaults to \code{NULL} and
#'   \code{burn_in} specified at the function \code{mHMM} will be used.
#' @param return_state_prob A logical scaler. Should the function, in addition
#'   to the most likely state sequence for each subject, also return the state
#'   probabilities at each point in time for each subject
#'   (\code{return_state_prob = TRUE}) or not (\code{return_state_prob =
#'   FALSE}). Defaults to \code{return_state_prob = FALSE}.
#'
#' @return The function \code{vit_mHMM} returns a matrix containing the most
#'   likely state at each point in time. The first column indicates subject id
#'   number. Hence, the id number is repeated over rows equal to the number of
#'   observations for that subject. The second column contains the most likely
#'   state at each point in time. If requested, the subsequent columns contain
#'   the state probabilities at each point in time for each subject.
#' @export
vit_mHMM_list <- function(
  models,
  s_data,
  burn_in = NULL,
  return_state_prob = FALSE
) {
  if (!inherits(models, 'mHMM_list')) {
    cli::cli_abort(c(
      "{.var models} must be an object of class {.cls mHMM_list}",
      "x" = "You provided an object of class {.cls {class(models)}}"
    ))
  }
  input <- models[[1]]$input
  n_subj <- input$n_subj
  if (is.null(burn_in)) {
    burn_in <- input$burn_in
  }
  J <- input$J
  m <- input$m
  id <- unique(s_data[, 1])
  n_vary <- input$n_vary
  data_distr <- input$data_distr
  n_dep <- input$n_dep
  state_seq <- lapply(n_vary, dif_matrix, cols = 2, data = NA_real_)
  probs <- vector(mode = "list", length = n_subj)
  if (data_distr == "categorical") {
    q_emiss <- input$q_emiss
    int_est_emiss <- rep(
      list(lapply(q_emiss - 1, dif_matrix, rows = m)),
      n_subj
    )
    est_emiss <- rep(list(lapply(q_emiss, dif_matrix, rows = m)), n_subj)
    for (s in 1:n_subj) {
      for (j in 1:n_dep) {
        emiss_int_bind <- lapply(models, \(x) {
          x$emiss_int_subj[[s]][[j]][(burn_in + 1):J, ]
        }) |>
          do.call('rbind', args = _)
        int_est_emiss[[s]][[j]][] <- matrix(
          apply(emiss_int_bind, 2, stats::median),
          byrow = TRUE,
          ncol = q_emiss[j] - 1,
          nrow = m
        )
        est_emiss[[s]][[j]][] <- mHMMbayes::int_to_prob(int_est_emiss[[s]][[j]])
      }
    }
  } else if (data_distr == "continuous") {
    est_emiss <- rep(
      list(rep(list(matrix(NA_real_, nrow = m, ncol = 2)), n_dep)),
      n_subj
    )
    for (s in 1:n_subj) {
      emiss_bind <- lapply(models, \(x) {
        x$PD_subj[[s]]$cont_emiss[((burn_in + 1):J), ]
      }) |>
        do.call('rbind', args = _)
      for (q in 1:n_dep) {
        est_emiss[[s]][[q]][] <- matrix(
          round(
            c(
              apply(emiss_bind[, ((q - 1) * m + 1):(q * m)], 2, stats::median),
              apply(
                emiss_bind[, (n_dep * m + (q - 1) * m + 1):(n_dep * m + q * m)],
                2,
                stats::median
              )
            ),
            3
          ),
          ncol = 2,
          nrow = m
        )
      }
    }
  } else if (data_distr == "count") {
    est_emiss <- rep(
      list(rep(list(matrix(NA_real_, nrow = m, ncol = 1)), n_dep)),
      n_subj
    )
    for (s in 1:n_subj) {
      for (q in 1:n_dep) {
        emiss_bind <- lapply(models, \(x) {
          x$PD_subj[[s]]$count_emiss[
            ((burn_in + 1):J),
            ((q - 1) * m + 1):(q * m)
          ]
        }) |>
          do.call('rbind', args = _)
        est_emiss[[s]][[q]][] <- matrix(
          round(apply(emiss_bind, 2, stats::median), 3),
          ncol = 1,
          nrow = m
        )
      }
    }
  }
  est_gamma <- vector('list', n_subj)
  for (s in 1:n_subj) {
    gamma_int_bind <- lapply(models, \(x) {
      x$gamma_int_subj[[s]][((burn_in + 1):J), ]
    }) |>
      do.call('rbind', args = _)
    est_gamma[[s]] <- matrix(
      apply(gamma_int_bind, 2, stats::median),
      ncol = m - 1,
      nrow = m,
      byrow = TRUE
    ) |>
      mHMMbayes::int_to_prob()
  }
  for (s in 1:n_subj) {
    emiss <- est_emiss[[s]] # extract emission parameters
    gamma <- est_gamma[[s]] # extract transition probabilities
    delta <- solve(t(diag(m) - gamma + 1), rep(1, m)) ## stationary probabilities
    n_vary_s <- n_vary[s]
    # obtain emission probabilities
    prob_emiss <- all1(
      x = as.matrix(s_data[s_data[, 1] == id[s], -1], ncol = n_dep),
      emiss = emiss,
      data_distr = data_distr,
      n_dep = n_dep
    )
    prob_emiss[is.na(prob_emiss)] <- 1 # impute 1 for missing values

    ## start viterbi algorithm (based on Zucchini 2nd ed, p. 90)
    xi <- matrix(NA, n_vary_s, m)
    foo <- delta * prob_emiss[1, ]
    xi[1, ] <- foo / sum(foo)
    for (t in 2:n_vary_s) {
      foo <- apply(xi[t - 1, ] * gamma, 2, max) * prob_emiss[t, ]
      xi[t, ] = foo / sum(foo)
    }
    iv <- numeric(n_vary_s)
    iv[n_vary_s] <- which.max(xi[n_vary_s, ])
    for (t in (n_vary_s - 1):1) {
      iv[t] = which.max(gamma[, iv[t + 1]] * xi[t, ])
    }
    state_seq[[s]][, 1] <- id[s] # column with ids
    state_seq[[s]][, 2] <- iv # save state probabilities

    ## compute forward probabilities if requested --> maybe need to think about instead returning filtered probabilities, but would need the backward algorithm for this
    if (return_state_prob) {
      if (data_distr == "categorical") {
        probs[[s]] <- cat_mult_fw_r_to_cpp(
          x = as.matrix(s_data[s_data[, 1] == id[s], ][, -1], ncol = n_dep),
          m = m,
          emiss = emiss,
          gamma = gamma,
          n_dep = n_dep,
          delta = NULL
        )[[1]]
      } else if (data_distr == "continuous") {
        probs[[s]] <- cont_mult_fw_r_to_cpp(
          x = as.matrix(s_data[s_data[, 1] == id[s], ][, -1], ncol = n_dep),
          m = m,
          emiss = emiss,
          n_dep = n_dep,
          gamma = gamma
        )[[1]]
      } else if (data_distr == "count") {
        probs[[s]] <- count_mult_fw_r_to_cpp(
          x = as.matrix(s_data[s_data[, 1] == id[s], ][, -1], ncol = n_dep),
          m = m,
          emiss = emiss,
          n_dep = n_dep,
          gamma = gamma
        )[[1]]
      }
    }
  }
  state_seq_m <- do.call(rbind, state_seq)
  colnames(state_seq_m) <- c("subj", "state")
  if (return_state_prob) {
    probs <- sapply(probs, t, simplify = FALSE)
    probs <- do.call(rbind, probs)
    colnames(probs) <- paste0("pr_state_", 1:m)
    state_seq_m <- cbind(state_seq_m, probs)
  }
  return(state_seq = as.data.frame(state_seq_m))
}
